### ISSUE TITLE
Luani Modul

### ISSUE THREAD

**Issue by Katzechrisu** [BauerPh/230V-WLAN-IO-Modul#2]
Hallo Philipp,
   ich wolltw über die Luani Seite schreiben, geht aber irgendwie nicht.
  
    habe deine Software zum testen auf ein ESP12 geflasht.
    Leider will es mein WLAN nicht. FRITZ!Box Fon WLAN.
    Liegt das am"!" ???
    Kann man das im Code ändern? Mit Tasmota läuft es top.
    Ich wollte mir mal deine Software anschauen. 
    Was kann sie im Vergleich zu Tasmota?
    Hast Du evtl. noch eine 1 und 2 Kanal Platine Rest?
    Was kostet die Fertigung einer Platine bei sag ich mal 20 Stück in etwa?

Gruß Christian

**Comment by BauerPh** [comment]
Hi,
ja es lag am "!", ich habe das gefixt. Es sollten nun alle Zeichen funktionieren bei der SSID.
Mit Tasmota hab ich mich noch nicht beschäftigt. Jedoch werde ich vermutlich die Software nicht lange weiterentwickeln. Denn espurna gefällt mir ganz gut und darauf werde ich wohl auch umsteigen.

Ich hätte evtl. noch Platinen (unbestückt!).
Bei elecrow kosten 10 Stück ca. 5$ + ca. 6$ Versand => ca. 8€

Gruß
Philipp

**Comment by Katzechrisu** [comment]
Hallo, 
Währe gut wenn Du mit evtl. eine 1-Kanal und eine 2-Kanal verkaufen könntest.

Hast du auch die Dateien und den Bestückungsplan?
Was hast Du gegen über denen Platinen von LUANI geändert? 
Oder hast du seine Patinen genommen und dann nur mit 1 Kanal bestückt. 

Ich suche auf jedenfalls eine Lösung die hinter den Schalter passt.


Mit freundlichen Grüßen 

Christian Zehren 



Kontakt:
xxx


Von meinem iphone gesendet
